[package]
name = "csvwriter"
version = "0.1.0"
authors = ["Daniel Kiluange <daniel.kiluange@ifood.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
